name: 'issue-creator'
description: 'Periodically create GitHub issue'
inputs:
  template-issue:
    description: 'Specify the issue number of the template in the repository. e.g. 1'
    required: true
  close-last-issue:
    description: 'If true, issue-creator closes the previous issue.'
    default: true
  check-before-create-issue:
    description: 'shell script'
    default: "echo 'OK'"
  token:
    default: ${{ github.token }}
  discussion:
    description: 'create discussion mode'
    default: false
  repository:
    description: 'e.g. rerost/issue-creator'
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: 'Dockerfile'
  args:
    - ./action.sh
    - ${{ inputs.repository }}
    - ${{ inputs.template-issue }}
    - ${{ inputs.close-last-issue }}
    - ${{ inputs.check-before-create-issue }}
    - ${{ inputs.token }}
    - ${{ inputs.discussion }}
