name: "Check actions work for issue"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: rerost/issue-creator@rerost/fix-actions-problem
        with:
          template-issue: 1
